=== Alex-notfound/DAI-Proyecto/HybridServer/src/configurationSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/configurationSchema"
	xmlns:tns="http://www.example.org/configurationSchema"
	elementFormDefault="qualified">

	<element name="configuration">
		<complexType>
			<sequence>
				<element name="connections"></element>
				<element name="database">
				</element>
				<element name="servers"></element>
			</sequence>
		</complexType>
	</element>

	<complexType name="database">
		<sequence>
			<element name="user"></element>
			<element name="password"></element>
			<element name="url"></element>
		</sequence>
	</complexType>

	<complexType name="connections">
		<sequence>
			<element name="http"></element>
			<element name="webservice"></element>
			<element name="numClients"></element>
		</sequence>
	</complexType>

	<complexType name="servers">
		<sequence>
			<element name="server"></element>
		</sequence>
	</complexType>
</schema>

=== Alex-notfound/DAI-Proyecto/HybridServer/src/configurationSchema.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:configuration xmlns:tns="http://www.example.org/configurationSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/configurationSchema configurationSchema.xsd ">
  <tns:connections>
    <tns:http>tns:http</tns:http>
    <tns:webservice>http://tempuri.org</tns:webservice>
    <tns:numClients>1</tns:numClients>
  </tns:connections>
  <tns:database>
    <tns:user>tns:user</tns:user>
    <tns:password>tns:password</tns:password>
    <tns:url>http://tempuri.org</tns:url>
  </tns:database>
  <tns:servers>
    <tns:server httpAddress="http://tempuri.org" name="" namespace="http://tempuri.org" service="" wsdl="http://tempuri.org"/>
  </tns:servers>
</tns:configuration>
